config/routes.rb
require File.expand_path("../../lib/catalog.rb", __FILE__)

Refinery::Application.routes.draw do
  match '/catalog', :as => 'catalog', :to => 'catalog#index'

  match '/catalog/filters', :as => 'catalog', :to => 'catalog#filters', :via => "GET"
  match '/catalog/filters', :as => 'catalog', :to => 'catalog#search', :via => "POST"


  # Make sure you restart your web server after changing the multi level setting.
  if ::Refinery::Catalog.multi_level?
    match "/catalog/:id/projects/:catalog_id/:image_id",
          :as => :catalog_image,
          :to => "catalog#show"

    match "/catalog/:id/projects/:catalog_id",
          :as => :catalog_project,
          :to => "catalog#show"
  else
    match "/catalog/:id/:image_id",
          :as => :catalog_image,
          :to => "catalog#show"

    match "/catalog/:id",
          :as => :catalog_project,
          :to => "catalog#show"
  end

  match '/catalog/:id', :as => 'catalog', :to => 'catalog#show'

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :catalog, :as => :catalog_types do
      resources :types, :as => :entry_attribute_types do
        resources :values, :as => :entry_attribute_type_values
      end
      resources :entries, :as => :catalog_entries do
        resources :attributes, :as => :entry_attributes
        collection do
          post :update_positions
        end
      end
      collection do
        get :empty_values
      end
    end
  end

end

app/controllers/admin/types_controller.rb
class Admin::TypesController < Admin::BaseController

  before_filter :load_catalog_type
  before_filter :load_entry_attribute_type, :only => [:show, :edit, :update, :destroy]

  def index
    @entry_attribute_types = @catalog_type.entry_attribute_types
  end

  def create
    @entry_attribute_type = @catalog_type.entry_attribute_types.build(params[:entry_attribute_type])
    if @entry_attribute_type.save
      @catalog_type.catalog_entries.each do |entry|
        entry_attribute = entry.entry_attributes.build(:catalog_type => @catalog_type,
                                                       :entry_attribute_type => @entry_attribute_type,
                                                       :entry_attribute_type_value => EntryAttributeTypeValue.empty_value(@entry_attribute_type))
        entry_attribute.save
      end

      flash[:notice] = t('flash.created.male', :name => EntryAttributeType.human_name)
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def show

  end

  def new
    @entry_attribute_type = EntryAttributeType.new
  end

  def edit

  end

  def update
    if @entry_attribute_type.update_attributes(params[:entry_attribute_type])
      flash[:notice] = t('flash.updated.male', :name => EntryAttributeType.human_name)
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @entry_attribute_type.destroy
    flash[:notice] = t('flash.destroyed.male', :name => EntryAttributeType.human_name)
    redirect_to :action => 'index'
  end

  protected

  def load_catalog_type
    @catalog_type = CatalogType.find_by_name(params[:catalog_type_id])
  end

  def load_entry_attribute_type
    @entry_attribute_type = EntryAttributeType.find(params[:id])
  end
end

app/views/admin/types/_form.html.erb
<% if Refinery.version < '0.9.9' %>
  <%= stylesheet_link_tag 'catalog' %>
  <%= javascript_include_tag 'catalog' %>
<% else %>
  <% content_for :javascripts, javascript_include_tag('catalog') %>
  <% content_for :stylesheets, stylesheet_link_tag('catalog') %>
<% end %>

<%= form_for [:admin, @catalog_type, @entry_attribute_type] do |f| %>
  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => f.object,
               :include_object_name => true
             }  %>
  <div id='catalog_body' class='field clearfix'>
    <%= f.required_label t('.name') %>
    <%= f.text_field :name, :class => "larger widest" %>
  </div>
  <div id='catalog_body' class='field clearfix'>
    <%= f.label t('.active') %>
    <%= f.check_box :active, :class => "" %>
  </div>

  <% new_record = @entry_attribute_type.new_record? %>
  <% unless new_record %>
    <%= link_to t(".attribute_type_values"), admin_catalog_type_entry_attribute_type_entry_attribute_type_values_url(@catalog_type, @entry_attribute_type), :class => "nothing_selected" %>
  <% end %>

  <%= render :partial => "admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => true,
               :path_prefix => 'catalog_type_',
               :cancel_url => admin_catalog_type_entry_attribute_types_url(@catalog_type),
               :delete_url => new_record ? '' : admin_catalog_type_entry_attribute_type_path(@catalog_type, @entry_attribute_type),
               :hide_delete => new_record
             } -%>

<% end %>

app/views/admin/types/_list.html.erb
<ul id='sortable_list'>
  <li class='clearfix' id="<%= dom_id(list) -%>">
    <div class='clearfix'>
      <span class='actions'>
        <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_catalog_type_entry_attribute_type_path(@catalog_type, list),
                   :title => t('.edit_this_entry') %>
        <%= link_to refinery_icon_tag('delete.png'), admin_catalog_type_entry_attribute_type_path(@catalog_type, list),
                   :class => "cancel confirm-delete",
                   :title => t('.confirm_delete_entry_title'),
                   :confirm => t('shared.admin.delete.message', :title => list.name),
                   :method => :delete %>
      </span>
      <%=h list.name %>
    </div>
  </li>
</ul>

app/views/admin/types/index.html.erb
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
  <% end %>
  <% unless @entry_attribute_types.nil? %>
    <%= render :partial => 'list', :collection => @entry_attribute_types %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong>
          <%= t('.no_attribute_types_yet') %>
        </strong>
      <% else %>
        <%= t('shared.admin.search.no_results') %>
      <% end %>
    </p>
  <% end %>
</div>
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search",
                 :locals => {:url => admin_catalog_type_entry_attribute_types_url(@catalog_type)} %>
    </li>
    <li>
      <%= link_to t('.create_new_attribute_type'), new_admin_catalog_type_entry_attribute_type_url(@catalog_type),
                  :class => "add_icon" %>
    </li>
  </ul>
</div>