config/routes.rb
require File.expand_path("../../lib/catalog.rb", __FILE__)

Refinery::Application.routes.draw do
  match '/catalog', :as => 'catalog', :to => 'catalog#index'

  match '/catalog/filters', :as => 'catalog', :to => 'catalog#filters', :via => "GET"
  match '/catalog/filters', :as => 'catalog', :to => 'catalog#search', :via => "POST"


  # Make sure you restart your web server after changing the multi level setting.
  if ::Refinery::Catalog.multi_level?
    match "/catalog/:id/projects/:catalog_id/:image_id",
          :as => :catalog_image,
          :to => "catalog#show"

    match "/catalog/:id/projects/:catalog_id",
          :as => :catalog_project,
          :to => "catalog#show"
  else
    match "/catalog/:id/:image_id",
          :as => :catalog_image,
          :to => "catalog#show"

    match "/catalog/:id",
          :as => :catalog_project,
          :to => "catalog#show"
  end

  match '/catalog/:id', :as => 'catalog', :to => 'catalog#show'

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :catalog, :as => :catalog_types do
      resources :types, :as => :entry_attribute_types do
        resources :values, :as => :entry_attribute_type_values
      end
      resources :entries, :as => :catalog_entries do
        resources :attributes, :as => :entry_attributes
        collection do
          post :update_positions
        end
      end
      collection do
        get :empty_values
      end
    end
  end

end

app/models/catalog_type.rb
class CatalogType < ActiveRecord::Base

  before_destroy :destroy_nested_resources

  has_many :catalog_entries
  has_many :entry_attributes
  has_many :entry_attribute_types

  validates_presence_of :name
  validates_uniqueness_of :name

  # call to gems included in refinery.
  has_friendly_id :name, :use_slug => true

  def title
    name
  end

  private

  def destroy_nested_resources
    entry_attributes.each do |attribute|
      attribute.destroy
    end

    entry_attribute_types.each do |attribute_type|
      attribute_type.destroy
    end

    catalog_entries.each do |entry|
      entry.destroy
    end
  end
end

app/controllers/admin/catalog_controller.rb
class Admin::CatalogController < Admin::BaseController

  before_filter :attributes_with_empty_values, :only => [:index, :empty_values]

  crudify :catalog_type

  def empty_values

  end

  private

  def attributes_with_empty_values
    @attributes_with_empty_values ||= EntryAttribute.joins(:entry_attribute_type_value).where("entry_attribute_type_values.value = ?", "empty")
  end

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController

  before_filter :load_page, :only => [:index, :show, :empty]

  def index
    @catalog_entries = CatalogEntry.all
  end

  def show
    begin
      @master_entry = if params[:id]
        CatalogEntry.find(params[:id])
      else
        CatalogEntry.where(:parent_id => nil).first
      end

      if ::Refinery::Catalog.multi_level?
        multi_level
      else
        single_level
      end

      begin
        image_index = (params[:image_id].presence || '0').to_i
        @image = @catalog_entry.images[image_index]
      rescue
        render :action => "empty"
      end
    rescue
      error_404
    end

    render :partial => "main_image", :layout => false if request.xhr?
  end

  def filters
    result = {}

    type_names = ActiveSupport::JSON.decode(params[:attribute_types])
    keys = EntryAttributeType.where(:name => type_names)
    keys.each do |key|
      result["by_#{key.name}"] = (EntryAttributeTypeValue.where(
          :entry_attribute_type_id => key.id).delete_if do |x| x.value == 'empty' end).map do
            |v| {:name => v.value, :id => v.id, :type => v.entry_attribute_type.name}
        end
    end

    render :json => result.to_json
  end

  def search
    attributes = EntryAttribute.all

    if params[:applied_filters]
      applied_filters = ActiveSupport::JSON.decode(params[:applied_filters])
      attributes = EntryAttribute.where(:entry_attribute_type_value_id => applied_filters.map do
          |x| x["id"]
        end)
    end

    render :json => (attributes.map do |x| x.catalog_entry end).uniq.to_json(
        :methods => [:color, :manufacturer, :composition])
  end

protected

  def entries_by_catalog_type(catalog_name)
    CatalogType.find_by_name(catalog_name).catalog_entries
  end

  def multi_level
    @catalog_entries = @master_entry.children
    @catalog_entry = if params[:catalog_id]
      @catalog_entries.find(params[:catalog_id])
    else
      @catalog_entries.first
    end
  end

  def single_level
    @catalog_entries = CatalogEntry.all
    @catalog_entry = @master_entry
  end

  def load_page
    @page = Page.find_by_link_url('/catalog', :include => [:parts])
  end

end

app/helpers/catalog_helper.rb
module CatalogHelper

  def catalog_image_link(master, catalog, image_index)
    if ::Refinery::Catalog.multi_level?
      catalog_image_url(master, catalog, image_index)
    else
      catalog_image_url(master, image_index)
    end
  end

  def link_to_catalog_image(master, catalog, image, index)
    link_to(image_fu(image, '96x96#c'),
            catalog_image_link(master, catalog, index))
  end

end

app/views/admin/catalog/_form.html.erb
<% if Refinery.version < '0.9.9' %>
  <%= stylesheet_link_tag 'catalog' %>
  <%= javascript_include_tag 'catalog' %>
<% else %>
  <% content_for :javascripts, javascript_include_tag('catalog') %>
  <% content_for :stylesheets, stylesheet_link_tag('catalog') %>
<% end %>

<%= form_for [:admin, @catalog_type] do |f| %>
  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => f.object,
               :include_object_name => true
             }  %>
  <div id='catalog_body' class='field clearfix'>
    <%= f.required_label t('.name') %>
    <%= f.text_field :name, :class => "larger widest" %>
  </div>

  <% new_record = @catalog_type.new_record? %>
  <% unless new_record %>
    <br/>
    <%= link_to t(".attribute_types"), admin_catalog_type_entry_attribute_types_url(@catalog_type), :class => "nothing_selected" %>
    <br/>
    <%= link_to t(".catalog_entries"), admin_catalog_type_catalog_entries_url(@catalog_type), :class => "nothing_selected" %>
  <% end %>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => true
             } -%>

<% end %>

app/views/admin/catalog/_list.html.erb
<ul id='sortable_list'>
  <li class='clearfix' id="<%= dom_id(list) -%>">
    <div class='clearfix'>
      <span class='actions'>
        <%= link_to refinery_icon_tag('application_go.png'), catalog_url(list), :target => "_blank",
                   :title => t('.view_live') %>
        <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_catalog_type_path(list),
                   :title => t('.edit_this_entry') %>
        <%= link_to refinery_icon_tag('delete.png'), admin_catalog_type_path(list),
                   :class => "cancel confirm-delete",
                   :title => t('.confirm_delete_entry_title'),
                   :confirm => t('shared.admin.delete.message', :title => list.name),
                   :method => :delete %>
      </span>
      <%=h list.name %>
    </div>
  </li>
</ul>

app/views/admin/catalog/empty_values.html.erb
<ul id='sortable_list'>
<% puts @attributes_with_empty_values.inspect %>
  <% @attributes_with_empty_values.each do |attribute| %>
    <li class='clearfix'>
      <div class='clearfix'>
        <span class='actions'>
          <%= link_to refinery_icon_tag('application_edit.png'),
                      edit_admin_catalog_type_catalog_entry_entry_attribute_path(attribute.catalog_type,
                                                                                      attribute.catalog_entry,
                                                                                      attribute),
                     :title => t('.edit_this_entry') %>
        </span>
        <%=h "#{attribute.catalog_type.title} - #{attribute.catalog_entry.title} - #{attribute.entry_attribute_type.name}" %>
      </div>
    </li>
  <% end %>
</ul>

app/views/admin/catalog/index.html.erb
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
  <% end %>
  <% unless @attributes_with_empty_values.blank? %>
  <% puts @attributes_with_empty_values.inspect %>
    <%= link_to t('.empty_values'), empty_values_admin_catalog_types_url %>
  <% end %>
  <% unless @catalog_types.nil? %>
    <%= render :partial => 'list', :collection => @catalog_types %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong>
          <%= t('.no_catalog_types_yet') %>
        </strong>
      <% else %>
        <%= t('shared.admin.search.no_results') %>
      <% end %>
    </p>
  <% end %>
</div>
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search",
                 :locals => {:url => admin_catalog_types_url} %>
    </li>
    <li>
      <%= link_to t('.create_new_catalog_entry'), new_admin_catalog_type_url,
                  :class => "add_icon" %>
    </li>
  </ul>
</div>