config/routes.rb
require File.expand_path("../../lib/catalog.rb", __FILE__)

Refinery::Application.routes.draw do
  match '/catalog', :as => 'catalog', :to => 'catalog#index'

  match '/catalog/filters', :as => 'catalog', :to => 'catalog#filters', :via => "GET"
  match '/catalog/filters', :as => 'catalog', :to => 'catalog#search', :via => "POST"


  # Make sure you restart your web server after changing the multi level setting.
  if ::Refinery::Catalog.multi_level?
    match "/catalog/:id/projects/:catalog_id/:image_id",
          :as => :catalog_image,
          :to => "catalog#show"

    match "/catalog/:id/projects/:catalog_id",
          :as => :catalog_project,
          :to => "catalog#show"
  else
    match "/catalog/:id/:image_id",
          :as => :catalog_image,
          :to => "catalog#show"

    match "/catalog/:id",
          :as => :catalog_project,
          :to => "catalog#show"
  end

  match '/catalog/:id', :as => 'catalog', :to => 'catalog#show'

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :catalog, :as => :catalog_types do
      resources :types, :as => :entry_attribute_types do
        resources :values, :as => :entry_attribute_type_values
      end
      resources :entries, :as => :catalog_entries do
        resources :attributes, :as => :entry_attributes
        collection do
          post :update_positions
        end
      end
      collection do
        get :empty_values
      end
    end
  end

end

app/models/catalog_type.rb
class CatalogType < ActiveRecord::Base

  before_destroy :destroy_nested_resources

  has_many :catalog_entries
  has_many :entry_attributes
  has_many :entry_attribute_types

  validates_presence_of :name
  validates_uniqueness_of :name

  # call to gems included in refinery.
  has_friendly_id :name, :use_slug => true

  def title
    name
  end

  private

  def destroy_nested_resources
    entry_attributes.each do |attribute|
      attribute.destroy
    end

    entry_attribute_types.each do |attribute_type|
      attribute_type.destroy
    end

    catalog_entries.each do |entry|
      entry.destroy
    end
  end
end

app/controllers/admin/catalog_controller.rb
class Admin::CatalogController < Admin::BaseController

  before_filter :attributes_with_empty_values, :only => [:index, :empty_values]

  crudify :catalog_type

  def empty_values

  end

  private

  def attributes_with_empty_values
    @attributes_with_empty_values ||= EntryAttribute.joins(:entry_attribute_type_value).where("entry_attribute_type_values.value = ?", "empty")
  end

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController

  before_filter :load_page, :only => [:index, :show, :empty]

  def index
    @catalog_entries = CatalogEntry.all
  end

  def show
    begin
      @master_entry = if params[:id]
        CatalogEntry.find(params[:id])
      else
        CatalogEntry.where(:parent_id => nil).first
      end

      if ::Refinery::Catalog.multi_level?
        multi_level
      else
        single_level
      end

      begin
        image_index = (params[:image_id].presence || '0').to_i
        @image = @catalog_entry.images[image_index]
      rescue
        render :action => "empty"
      end
    rescue
      error_404
    end

    render :partial => "main_image", :layout => false if request.xhr?
  end

  def filters
    result = {}

    type_names = ActiveSupport::JSON.decode(params[:attribute_types])
    keys = EntryAttributeType.where(:name => type_names)
    keys.each do |key|
      result["by_#{key.name}"] = (EntryAttributeTypeValue.where(
          :entry_attribute_type_id => key.id).delete_if do |x| x.value == 'empty' end).map do
            |v| {:name => v.value, :id => v.id, :type => v.entry_attribute_type.name}
        end
    end

    render :json => result.to_json
  end

  def search
    attributes = EntryAttribute.all

    if params[:applied_filters]
      applied_filters = ActiveSupport::JSON.decode(params[:applied_filters])
      attributes = EntryAttribute.where(:entry_attribute_type_value_id => applied_filters.map do
          |x| x["id"]
        end)
    end

    render :json => (attributes.map do |x| x.catalog_entry end).uniq.to_json(
        :methods => [:color, :manufacturer, :composition])
  end

protected

  def entries_by_catalog_type(catalog_name)
    CatalogType.find_by_name(catalog_name).catalog_entries
  end

  def multi_level
    @catalog_entries = @master_entry.children
    @catalog_entry = if params[:catalog_id]
      @catalog_entries.find(params[:catalog_id])
    else
      @catalog_entries.first
    end
  end

  def single_level
    @catalog_entries = CatalogEntry.all
    @catalog_entry = @master_entry
  end

  def load_page
    @page = Page.find_by_link_url('/catalog', :include => [:parts])
  end

end

app/helpers/catalog_helper.rb
module CatalogHelper

  def catalog_image_link(master, catalog, image_index)
    if ::Refinery::Catalog.multi_level?
      catalog_image_url(master, catalog, image_index)
    else
      catalog_image_url(master, image_index)
    end
  end

  def link_to_catalog_image(master, catalog, image, index)
    link_to(image_fu(image, '96x96#c'),
            catalog_image_link(master, catalog, index))
  end

end

app/views/catalog/_main_image.html.erb
<%= image_fu @image, '600x512', :id => "catalog_main_image" unless @image.nil? %>

app/views/catalog/empty.html.erb
<% content_for :title, "#{@master_entry.title} - " %>
<% content_for :head, stylesheet_link_tag('catalog') %>

<% content_for :body_content_title, @master_entry.title %>
<% content_for :body_content_left do %>
  <p>
    <em><%= t(:catalog_no_entries, :default => "We haven't entered anything in for this project yet.") %></em>
  </p>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/catalog/index.html.erb
<% content_for :javascript_libraries, jquery_include_tags(:jquery_ui => true) %>
<% content_for :after_javascript_libraries, javascript_include_tag('underscore.js') %>
<% content_for :after_javascript_libraries, javascript_include_tag('jquery.json-2.3.min.js') %>
<% content_for :after_javascript_libraries, stylesheet_link_tag("jquery-ui") %>

<% content_for :after_javascript_libraries, javascript_include_tag('catalog.index.js') %>
<% content_for :after_javascript_libraries, stylesheet_link_tag("blueprint/screen.css") %>
<% content_for :after_javascript_libraries, stylesheet_link_tag("blueprint/print.css") %>
<% content_for :after_javascript_libraries, javascript_include_tag('html5.js') %>
<% content_for :after_javascript_libraries, javascript_include_tag('engine.js') %>


  <div id="wrapper0">
			<div class="container">
				<div class="article-wrapper">
					<article class="filters">
						<div class="flt-cont">
							<div class="flt-variants">
								<div class="flt-variants-top"></div>
								<div class="flt-variants-middle">

									<ul class="flt-choices">
										<li>
											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_0"></label>
											<input type="checkbox" class="check" checked="checked" id="id_check_0" />
											<h4>Хлопок</h4>
										</li>
										<li>

											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_1"></label>
											<input type="checkbox" class="check" checked="checked" id="id_check_1" />
											<h4>Хлопок</h4>
										</li>
										<li>
											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_2"></label>

											<input type="checkbox" class="check" id="id_check_2" />
											<h4>Хлопок</h4>
										</li>
										<li>
											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_3"></label>
											<input type="checkbox" class="check" checked="checked" id="id_check_3" />
											<h4>Хлопок</h4>

										</li>
										<li>
											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_4"></label>
											<input type="checkbox" class="check" id="id_check_4" />
											<h4>Хлопок</h4>
										</li>
										<li>

											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_5"></label>
											<input type="checkbox" class="check" id="id_check_5" />
											<h4>Хлопок</h4>
										</li>
										<li>
											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_6"></label>

											<input type="checkbox" class="check" id="id_check_6" />
											<h4>Хлопок</h4>
										</li>
										<li>
											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_7"></label>
											<input type="checkbox" class="check" id="id_check_7" />
											<h4>Хлопок</h4>

										</li>
										<li>
											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_8"></label>
											<input type="checkbox" class="check" id="id_check_8" />
											<h4>Хлопок</h4>
										</li>
										<li>

											<img src="/img/stub/cotton_filter.jpg" alt="" />
											<label for="id_check_9"></label>
											<input type="checkbox" class="check" id="id_check_9" />
											<h4>Хлопок</h4>
										</li>
									</ul>
									<a class="toggle" href="javascript:;">Свернуть</a>
									<div class="flt-variants-bottom"></div>

								</div>
								<div class="flt-variants-left"></div>
								<div class="flt-variants-right"></div>
							</div>
							<ul class="flt-tabs">
								<li class="active"><a href="javascript:;">Состав</a><span class="closure"><span></span></span></li>
								<li><a href="javascript:;">Цвет</a><span class="closure"><span></span></span></li>
								<li><a href="javascript:;">Производитель</a><span class="closure"><span></span></span></li>

							</ul>
							<div class="flt-checked">
								<div class="flt-checked-cont">
									<div class="flt-checked-box box3">
										<div class="head">Состав:</div>
										<ul>
											<li>Хлопок<a href="javascript:;"></a></li>
											<li>Лен<a href="javascript:;"></a></li>

											<li>Кашемир<a href="javascript:;"></a></li>

										</ul>
										<div class="right-line"></div>
									</div>
									<div class="flt-checked-box box3">
										<div class="head">Цвет:</div>
										<ul>
										</ul>

										<div class="right-line"></div>
									</div>
									<div class="flt-checked-box box3">
										<div class="head">Производитель:</div>
										<ul>
										</ul>
										<div class="right-line"></div>
									</div>

								</div>
								<div class="flt-variants-left thin"></div>
								<div class="flt-variants-right thin"></div>
							</div>
							<div class="article-shadow"></div>
						</div>
						<div class="flt-table">
							<table>
								<thead>

									<tr>
										<th style="width:120px;">Артикул<span class="dn"></span></th>
										<th style="width:230px;">Наименование</th>
										<th style="width:140px;">Состав</th>
										<th style="width:90px;">Цвет</th>
										<th>Производитель</th>

									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Артикул</td>
										<td>Наименование</td>
										<td>Состав</td>

										<td>Цвет</td>
										<td>Производитель</td>
									</tr>
									<tr>
										<td>Артикул</td>
										<td>Наименование</td>
										<td>Состав</td>

										<td>Цвет</td>
										<td>Производитель</td>
									</tr>
									<tr>
										<td>Артикул</td>
										<td>Наименование</td>
										<td>Состав</td>

										<td>Цвет</td>
										<td>Производитель</td>
									</tr>
									<tr>
										<td>Артикул</td>
										<td>Наименование</td>
										<td>Состав</td>

										<td>Цвет</td>
										<td>Производитель</td>
									</tr>
									<tr>
										<td>Артикул</td>
										<td>Наименование</td>
										<td>Состав</td>

										<td>Цвет</td>
										<td>Производитель</td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="article-bottom-hr"></div>
						<div class="left-shadow"></div><div class="right-shadow"></div>

					</article>
				</div>
				<div class="article-shadow"></div>
			<div class="hd-bottom"></div>

		</div>

app/views/catalog/show.html.erb
<% content_for :title, @catalog_entry.title %>

<% content_for :body_content_title do %>
  <span><%= @master_entry.title %></span>

  <%= select(:catalog_entry, :to_param,
             @catalog_entries.collect{|entry|
               [entry.title, entry.to_param]
             }) if @catalog_entries.many? %>
<% end %>

<% content_for :body_content_left do %>
  <div id='catalog_main_image_container'>
    <%= render :partial => "main_image" %>
  </div>
<% end %>

<% content_for :body_content_right do %>
  <h2><%= @catalog_entry.title %></h2>
  <ul id='catalog_images'>
    <% @catalog_entry.images.each_with_index do |image, index| %>
      <li class="<%= cycle('odd', 'even') %> #{index == params[:image_id].to_i) ? 'selected' : 'other'}">
        <%= link_to_catalog_image(@master_entry, @catalog_entry, image, index) %>
      </li>
    <% end %>
  </ul>
<% end %>

<div class='catalog'>
  <%= render :partial => "/shared/content_page" %>
</div>

<% content_for :head do %>
  <%= stylesheet_link_tag('catalog') %>
  <%# remove the jquery_include_tags call if jquery is included in your layout.
  %>
  <%= jquery_include_tags(:include_ui => false) %>
  <%= javascript_include_tag 'catalog' %>
  <script type='text/javascript'>
    var catalog_entry_url = "<%= catalog_project_url(@master_entry, @catalog_entry) if ::Refinery::Catalog.multi_level? %>";
  </script>
<% end %>