config/routes.rb
require File.expand_path("../../lib/catalog.rb", __FILE__)

Refinery::Application.routes.draw do
  match '/catalog', :as => 'catalog', :to => 'catalog#index'

  match '/catalog/filters', :as => 'catalog', :to => 'catalog#filters', :via => "GET"
  match '/catalog/filters', :as => 'catalog', :to => 'catalog#search', :via => "POST"


  # Make sure you restart your web server after changing the multi level setting.
  if ::Refinery::Catalog.multi_level?
    match "/catalog/:id/projects/:catalog_id/:image_id",
          :as => :catalog_image,
          :to => "catalog#show"

    match "/catalog/:id/projects/:catalog_id",
          :as => :catalog_project,
          :to => "catalog#show"
  else
    match "/catalog/:id/:image_id",
          :as => :catalog_image,
          :to => "catalog#show"

    match "/catalog/:id",
          :as => :catalog_project,
          :to => "catalog#show"
  end

  match '/catalog/:id', :as => 'catalog', :to => 'catalog#show'

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :catalog, :as => :catalog_types do
      resources :types, :as => :entry_attribute_types do
        resources :values, :as => :entry_attribute_type_values
      end
      resources :entries, :as => :catalog_entries do
        resources :attributes, :as => :entry_attributes
        collection do
          post :update_positions
        end
      end
      collection do
        get :empty_values
      end
    end
  end

end

app/controllers/admin/entries_controller.rb
class Admin::EntriesController < Admin::BaseController

#ToDo:
#  crudify :catalog_entry,
#          :order => 'lft ASC',
#          :conditions => {:parent_id => nil},
#          :sortable => true

  before_filter :load_catalog_type
  before_filter :load_catalog_entry, :only => [:show, :edit, :update, :destroy]

  def index
    @catalog_entries = @catalog_type.catalog_entries
  end

  def create
    @catalog_entry = @catalog_type.catalog_entries.build(params[:catalog_entry])
    if @catalog_entry.save
      @catalog_type.entry_attribute_types.each do |attribute_type|
        entry_attribute = @catalog_entry.entry_attributes.build(:catalog_type => @catalog_type,
                                              :entry_attribute_type => attribute_type,
                                              :entry_attribute_type_value => EntryAttributeTypeValue.empty_value(attribute_type))
        entry_attribute.save
      end

      flash[:notice] = t('flash.created.male', :name => CatalogEntry.human_name)
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def show

  end

  def new
    @catalog_entry = CatalogEntry.new
  end

  def edit

  end

  def update
    if @catalog_entry.update_attributes(params[:catalog_entry])
      flash[:notice] = t('flash.updated.male', :name => CatalogEntry.human_name)
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @catalog_entry.destroy
    flash[:notice] = t('flash.destroyed.male', :name => CatalogEntry.human_name)
    redirect_to :action => 'index'
  end

  protected

  def load_catalog_type
    @catalog_type = CatalogType.find_by_name(params[:catalog_type_id])
  end

  def load_catalog_entry
    @catalog_entry = CatalogEntry.find(params[:id])
  end
end

app/views/admin/entries/_form.html.erb
<% if Refinery.version < '0.9.9' %>
  <%= stylesheet_link_tag 'catalog' %>
  <%= javascript_include_tag 'catalog' %>
<% else %>
  <% content_for :javascripts, javascript_include_tag('catalog') %>
  <% content_for :stylesheets, stylesheet_link_tag('catalog') %>
<% end %>

<%= form_for([:admin, @catalog_type, @catalog_entry]) do |f| %>
  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => f.object,
               :include_object_name => true
             }  %>
  <div id='catalog_body' class='field clearfix'>
    <%= f.required_label t('.title') %>
    <%= f.text_field :title, :class => "larger widest" %>
  </div>
  <% unless RefinerySetting.find_or_set(:catalog_has_no_index, true)%>
    <div class='field'>
      <%= f.label :image -%>
      <%= render :partial => "/shared/admin/image_picker", :locals => {
        :f => f,
        :field => :title_image_id,
        :image => @catalog_entry.title_image,
        :toggle_image_display => false
      } %>
    </div>
  <% end %>
  <div class='field clearfix'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content'>
      <ul id='page_parts'>
        <li class='ui-state-default ui-state-active'>
          <%= link_to t('.content'), '#page_part_content'%>
        </li>
        <li class='ui-state-default'>
          <%= link_to t('.images'), '#catalog_image_picker'%>
        </li>
      </ul>
    </div>
    <div id='page_part_editors'>
      <div id='page_part_content' class='page_part'>
        <%= f.text_area :body, :class => "wymeditor widest", :rows => 7 %>
      </div>
      <div class='page_part wym_skin_refinery' id='catalog_image_picker'>
        <div class='wym_area_top'>
          <span class='clearfix label_inline_with_link'>
            <%= link_to t('.add_another_image').html_safe,
                        insert_admin_images_url(:dialog => true,
                                                :width => 866,
                                                :height => 510,
                                                :callback => "image_added"),
                        :id => "add_image_link" %>
          </span>
        </div>
        <div class='wym_box field images_field'>
          <ul id='catalog_images' class='clearfix catalog_entry_images'>
            <%= f.fields_for :images do |image_form| %>
              <li id='image_<%= image_form.object.id %>'>
                <%= image_form.hidden_field :id %>
                <%= image_fu image_form.object, '135x135#c' %>
              </li>
            <% end %>
            <li class='empty'>
              <%= hidden_field_tag "catalog_entry[images_attributes][#{@catalog_entry.images.size}][id]" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% if (nested_catalogs = nested_set_options(CatalogEntry, @catalog_entry) {|i| "#{'-' * i.level} #{i.title}" }).present? %>
    <div class='field'>
      <%= f.label t('.parent') %>
      <%= f.select :parent_id, nested_catalogs, :include_blank => true %>
    </div>
  <% end %>

  <% new_record = @catalog_entry.new_record? %>
  <br/>
  <% unless new_record %>
    <%= link_to t(".entry_attributes"), admin_catalog_type_catalog_entry_entry_attributes_url(@catalog_type, @catalog_entry), :class => "nothing_selected" %>
  <% end %>

  <%= render :partial => "admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => true,
               :cancel_url => admin_catalog_type_catalog_entries_url(@catalog_type),
               :delete_url => new_record ? '' : admin_catalog_type_catalog_entry_path(@catalog_type, @catalog_entry),
               :hide_delete => new_record
             } -%>

<% end %>

app/views/admin/entries/_list.html.erb
<%
  branch = if list === @catalog_entries.first
    "branch_start"
  elsif list === @catalog_entries.last or (list.parent and list === list.parent.children.last)
    "branch_end"
  end
-%>
<li class='clearfix record<%= " #{branch}" %>' id="<%= dom_id(list) -%>">
  <div class='clearfix'>
    <span class='actions'>
      <% url = (::Refinery::Catalog.multi_level? && list.parent ? catalog_project_url(list.parent, list) : catalog_url(list))  %>
      <%= link_to refinery_icon_tag('application_go.png'), url, :target => "_blank",
                 :title => t('.view_live') %>
      <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_catalog_type_catalog_entry_path(@catalog_type, list),
                 :title => t('.edit_this_entry') %>
      <%= link_to refinery_icon_tag('delete.png'), admin_catalog_type_catalog_entry_path(@catalog_type, list),
                 :class => "cancel confirm-delete",
                 :title => t('.confirm_delete_entry_title'),
                 :confirm => t('shared.admin.delete.message', :title => list.title),
                 :method => :delete %>
    </span>
    <%=h list.title %>
  </div>
  <% if (children = list.children).any? %>
    <ul<%= " class='nested'" %>>
      <%= render :partial => 'list', :collection => children %>
    </ul>
  <% end %>
</li>

app/views/admin/entries/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'list', :collection => @catalog_entries %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
           :locals => {:continue_reordering => (defined?(continue_reordering) ? continue_reordering : true)} %>

app/views/admin/entries/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/entries/index.html.erb
<div id='records' class='tree'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
  <% end %>
  <% unless @catalog_entries.nil? %>
    <%= render :partial => 'sortable_list' %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong>
          <%= t('.no_catalog_entries_yet') %>
        </strong>
      <% else %>
        <%= t('shared.admin.search.no_results') %>
      <% end %>
    </p>
  <% end %>
</div>
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search",
                 :locals => {:url => admin_catalog_type_catalog_entries_url(@catalog_type)} %>
    </li>
    <li>
      <%= link_to t('.create_new_catalog_entry'), new_admin_catalog_type_catalog_entry_url(@catalog_type),
                  :class => "add_icon" %>
    </li>
   <% if @catalog_entries.many? and !searching? %>
    <li>
      <%= link_to t('.reorder_catalog'), "",
                  :id => "reorder_action",
                  :class => "reorder_icon" %>
      <%= link_to t('.reorder_catalog_done'), "",
                  :id => "reorder_action_done",
                  :style => "display: none;",
                  :class => "reorder_icon" %>
    </li>
   <% end %>
  </ul>
</div>
<% content_for :head_after_javascript_libraries,
               javascript_include_tag('refinery/nestedsortables.js') if Refinery.version < '0.9.9' -%>
<%= render :partial => "/shared/admin/make_sortable",
           :locals => { :tree => ::Refinery::Catalog.multi_level? } if @catalog_entries.many? %>

app/views/admin/entries/new.html.erb
<%= render :partial => "form" %>